# Generated by Django 4.1.1 on 2022-09-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeaccounts',
            name='uri',
            field=models.URLField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='warehouseaccounts',
            name='uri',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
