# Generated by Django 4.1.1 on 2022-09-12 00:11

from django.db import migrations, models
import store_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_alter_storeorder_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeorder',
            name='id',
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='order_number',
            field=models.CharField(db_index=True, default=store_app.models.random_order, max_length=250, primary_key=True, serialize=False, unique=True),
        ),
    ]
