# Generated by Django 4.1.1 on 2022-09-12 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_remove_storeorder_id_alter_storeorder_order_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreOrder',
            new_name='Order',
        ),
    ]
