# Generated by Django 4.1.1 on 2022-09-12 00:14

from django.db import migrations, models
import warehouse_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0002_alter_storeaccounts_uri_alter_warehouseaccounts_uri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseorder',
            name='id',
        ),
        migrations.AlterField(
            model_name='warehouseorder',
            name='order_number',
            field=models.CharField(db_index=True, default=warehouse_app.models.random_order, max_length=250, primary_key=True, serialize=False, unique=True),
        ),
    ]
