# Generated by Django 4.1.1 on 2022-09-12 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0003_remove_warehouseorder_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WarehouseOrder',
            new_name='Order',
        ),
    ]
