# Generated by Django 4.1.1 on 2022-09-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0004_rename_warehouseorder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeaccounts',
            name='uri',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='warehouseaccounts',
            name='uri',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
